### PR TITLE
removed hardcoded implementation of tag format. bug resolved

### PR DESCRIPTION
**Pull request by rushi-growexxer**

### CODE REVIEW

**Comment by xotahal** [comment]
I am not sure this is bug. Git always returns that format. Just try to run `git describe --tags`

**Comment by rushi-growexxer** [comment]
Dear Sir, 
Case 1 : Tag Format is v2.3.5-12-f8g99g
the issue is when you extract the tag name from the tag (of format v2.3.5-12-f8g99g) using split and strip, it gives the expected result. But when you pass that tag_name to the function get_last_hash, it cannot retrieve the latest hash because no such tags exist for name v2.3.5.

Case 2 : Tag Format is v2.3.5 only
And when the format is v2.3.5 only, tag_name returns the empty string after performing split and strip.

And the main issue due to this is, that it always fetches commit from 1st commit of the repo and not from the latest tag as it couldn't find the latest hash and return default hash of the first commit.

I spent a couple of days to find and fixing the issue and finally arrived at this result and generated a PR for it. I have tested it and I think it's now working as per expectations. You also test it from your side and let me the status.

Your work is indeed appreciable. Thanks.

**Comment by xotahal** [comment]
I am still confused. I am using the tag names `v2.3.5` and it works as expected.

This piece of code https://github.com/xotahal/fastlane-plugin-semantic_release/blob/master/lib/fastlane/plugin/semantic_release/actions/analyze_commits.rb#L23 returns `v2.3.5-12-f8g99g` for tag `v2.3.5`. This is how the `git describe` works. See: https://git-scm.com/docs/git-describe#_examples

The only "problem" I can think of is a format of `match` parameters that you guys might be using instead of the default one. https://github.com/xotahal/fastlane-plugin-semantic_release/blob/master/lib/fastlane/plugin/semantic_release/actions/analyze_commits.rb#L23

Can you please send how that command looks like for you? `command = "git describe --tags --match=#{params[:match]}"`

Appreciate the help. Thank you 🙏

**Comment by rushi-growexxer** [comment]
Thanks for update Sir. I found the error. It was some mistake from my side.
You designed a great plugin. Thank You.

**Comment by xotahal** [comment]
Can you please share what the error was? If someone has the same problem.

**Comment by rushi-growexxer** [comment]
The issue was, I was testing the deploy and this plugin locally. So I was running `fastlane android beta` locally without any commits. So tagging on the same commit was giving issues and another related issue of fetching commits based on the previous tag.
Now it's solved and working.

**Pull request closed without merging**
