### PR TITLE
Fix for analyze_commits throwing a non-zero error code

### LINKED ISSUE #15: analyze_commits throws a non-zero error code
```
185 +------+------------------+-------------+
186 |           fastlane summary            |
187 +------+------------------+-------------+
188 | Step | Action           | Time (in s) |
189 +------+------------------+-------------+
190 | 1    | default_platform | 0           |
191 | 💥   | analyze_commits  | 0           |
192 +------+------------------+-------------+
193 ERROR [2019-11-25 20:53:18.97]: fastlane finished with errors
194 Looking for related GitHub issues on fastlane/fastlane...
195 Search query: Shell command exited with exit status 127 instead of 0.
```

### PR DESCRIPTION
**Pull request by karlmarxlopez**
Resolves #15

### CODE REVIEW

**Comment by xotahal** [comment]
@karlmarxlopez Sorry mate about this super delay. Thanks for this. I am trying to understand the problem.

1. Why do you get more than one hash when you ask for commits with 0 parents? Can I get access to such a repo?
2. Why do we think that `first` commit (hash) is the one we want?

**Comment by karlmarxlopez** [comment]
Hi, no worries.

1. I don't know why we were getting > 1 hash, it is working before then suddenly it does not work? Maybe it is related to the new branch we've created.
2. I've just assumed that the first commit is the last commit since the `tag`, since the hashes are in descending order.

**Comment by xotahal** [comment]
Do you have any kind of mono repo? That’s probably the reason why you’re getting more hashes. Anyway, once you create a first tag you stop having this problem right?

**Comment by karlmarxlopez** [comment]
We're not using monorepo.

If my memory is correct, I'll try to describe what we've done when we
encountered this issue.

1. We've started with 2 branches, master and internal.
2. Several internal releases where done, so there were several
android/internal/x.y.z tags
3. Then when an internal version is ready for alpha deployment, we've
created an alpha branch and did a deployment there.
4. This is where all the problems started

**Comment by xotahal** [comment]
@karlmarxlopez Hey mate I "fixed" this on 1.9.1

And I am writing "fixed" because it is hard to fix :) It is very likely caused by the way how we pull the repo. If we pull only part of the history for example (git fetch **--depth=1** ...) it won't find very fist commit on the branch. And that means it won't work for codepush.

In my case I did this:
`git fetch --no-tags ...`
`git fetch --depth=1 origin +refs/tags/*:refs/tags/*`

I removed `--depth=1` and everything works fine.

### The "fix":
- when it gets more than one hash as result of `git rev-list ...` it displays error (and suggestion how to fix that) and ends with `is_codepush_friendly = false`

Let me know if you were able to fix this by fetching complete history of git repo. Cheers 🙏

**Pull request closed without merging**
